messages:
  prefix: "&b&l[&9SafeCombat&b&l]"
  must-be-player: "&cVous devez être un joueur pour exécuter cette commande."
  args-wrong: "&cUn ou plusieurs arguments sont incorrects."
  player-offline: "&cLe joueur que vous avez renseigné n'est pas en ligne."
  not-enough-args: "&cLe nombre d'argument n'est pas correct."
  fight:
    cant-enter-zone: "&cVous êtes en &lcombat &r&c! Vous ne pouvez pas entrer dans cette zone."
    enter: "&6Vous êtes en combat, n'essayez pas de fuir."
    finished: "&aVous n'êtes plus en combat."
    command-banned: "&cCette commande est bannie en combat. Veuillez attendre de ne plus l'être."
  protection:
    finished: "&eVotre protection a pris fin. Vous pouvez désormais &cattaquer &eet &cêtre attaqué &epar d'autres joueurs."
    protected: "&aVous avez obtenu une protection. Vous ne pouvez plus attaquer ni être attaqué. Pour y renoncer, faites la commande 
      &e/protection disable&a."
    join: "&6Rappel : &eVous bénéficiez d'une protection. Vous ne pouvez &cni attaquer, ni être attaqué&e. Pour y renoncer, faites la commande 
      &c/protection disable&e."
    not-protected: "&cVous n'êtes pas protégé."
    try-again: "&cÉchec de la désactivation de votre protection, respectez bien les consignes."
    cancelled: "&aOpération annulée."
    removed: "&e&lVotre protection a été supprimée avec succès."
    removed-admin: "&e&lVotre protection a été supprimée par un administrateur."
    target-removed: "&aLa protection du joueur a été supprimée avec succès."
    cancellation-started: "&eLa procédure de désactivation de la protection a commencé. Pour l'annuler, écrivez &ccancel &edans le tchat. 
      &ePour désactiver votre protection, écrivez à l'identique \"&cJe souhaite ne plus bénéficier de ma protection&e\". &6Cet acte est irréversible. 
      La perte de votre protection vous permet d'attaquer et d'être attaqué."
    already: "&cCe joueur est déjà sous l'effet d'une protection."
pvp:
  # Time, in seconds, to stop be considered in PvP
  duration: 30
  # Time, in seconds, to be considered to have leaved the fight
  disconnection: 10
  # Time, in hours, a new player is protected and couldn't attack
  newbie-protection: 48
  # Time, in seconds, a respawned player is protected and couldn't attack
  respawn-protection: 30
  trident:
    # Cooldown a trident material to the player if it has a riptide enchant
    riptide-cooldown: true
    # Time, in seconds
    cooldown-time: 15
  enderpearl:
    # Set a custom cooldown to ender pearl when thrown
    custom-cooldown: true
    # Time, in seconds
    cooldown-time: 10
# Banned commands if the player is in pvp
banned-commands:
  - "tpyes"
  - "etpyes"
  - "tpaccept"
  - "etpaccept"
  - "sethome"
  - "esethome"
  - "createhome"
  - "ecreatehome"
  - "home"
  - "ehome"
  - "spawn"
  - "espawn"
  - "f home"

# DO NOT TOUCH
protected-players:
