name: SafeCombat
version: '${project.version}'
main: fr.keykatyu.safecombat.Main
api-version: '1.20'
description: '${project.description}'
softdepend:
  - WorldGuard
  - Factions
commands:
  protection:
    description: Manage player PvP protection.
    aliases:
      - pvp-protection