name: SafeCombat
version: '${project.version}'
main: fr.gameofarkadia.safecombat.Main
api-version: '1.21'
description: '${project.description}'

depend:
  - ArkadiaLib
  - HuskSync
  - PterodactylAPI

commands:
  protection:
    description: Allow player to disable their protection.
    usage: /protection <status|disable>

  safecombat-admin:
    description: Admin command to manage players PvP protection status.
    usage: /safecombat-admin <player> <status|disable>
    permission: safecombat.command.admin

permissions:
  # wildcard
  safecombat.*:
    description: Grants all permissions for SafeCombat.
    default: op
    children:
      safecombat.command.admin: true

  # admin command
  safecombat.command.admin:
    description: Allows admins to manage players PvP protection status.
    default: op